### ISSUE TITLE
objdictの改修

### ISSUE THREAD

**Issue by 6in** [6in/python-commander#19]
プレースホルダでの値の取得ができるようにする

**Comment by 6in** [comment]
* スクリプトのコマンドパラメータの取得において、プレースホルダの取得ができるようにする。
```
parameters:
  test: abc

commands:
  - type: echo
    parameters:
      test: ${test}  
```

* プレースホルダを取得するには、プロパティアクセスする。
* キー名だと元の値になる。
```
params = conetxt.get_parameters()
params.test   // abcが返却
params['test'] // ${test} が返却
```
