### ISSUE TITLE
Sampleコマンド改修

### ISSUE THREAD

**Issue by 6in** [6in/python-commander#50]
サンプルデータをパラメータで定義できるようにする。

CSV／JSON／YAMLで定義できるようにする

```
- type: sample
  parameters:
    sample_data: |
       データ
```
