### ISSUE TITLE
コマンド仕様Yamlのパラメータのtype指定を複数指定できるようにする。

### ISSUE THREAD

**Issue by 6in** [6in/python-commander#63]
```
parameters:
  data_type:
    type:  
      - sting
      - bool
      - list
```
