### ISSUE TITLE
正規表現コマンドの追加

### ISSUE THREAD

**Issue by 6in** [6in/python-commander#8]

**Comment by 6in** [comment]
パラメータイメージ
```
  - type: regexp
    comment: 正規表現でのマッチング
    parameters:
      target.key: line
      rules:
        - name: ruleName1
          comment: ルール1
          ignore_case: no
          regexp: |
            #def xxx
            #def yyy
            (xxx)(yyy)
          group_names:
            # グループ番号順に格納するキー名を指定
            - key1
            - key2
        - name: ruleName2
          comment: ルール2
          ignore_case: no
          regexp: |
            #def xxx
            #def zzz
            (xxx)(zzz)
          group_names:
            # グループ番号指定の場合
            1: key1
            2: key3
        - name: ruleName3
          comment: ルール3
          ignore_case: no
          regexp: |
            #def xxx
            #def zzz
            (?P<key1>xxx)(?P<key2>zzz)
          # group_names: グループ指定は、groupdictから取得する(https://note.nkmk.me/python-re-match-object-span-group/)



```
